#!/bin/bash
source "./functions.sh"

#
# Basher :)
#

plugin 'vim'
plugin 'git'
plugin 'github-two-factor'
plugin 'grep'
plugin 'colors'
plugin 'history'
plugin 'github.com/wtty-fool/basher-plugin'
# or gitlab, bitbucket etc

# commands in functions.sh
plugin - start
plugin_install
plugin_uninstall
plugin_update

